version: "3"

services:
  sqldata: 
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlServer
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
